<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <groupId>oAT</groupId>
    <artifactId>oAT-agent</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>oAT-agent-core</module>
        <module>oAT-agnet-shaded</module>
    </modules>

    <!-- 定义系统属性 -->
    <properties>
        <maven.compiler.source>8</maven.compiler.source><!-- compile插件 -->
        <maven.compiler.target>8</maven.compiler.target><!-- compile插件 -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- compile插件 -->
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <locales>en_US</locales>
        <!-- site插件 -->
        <argLine>-XX:-UseSplitVerifier</argLine>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
