CREATE TABLE IF NOT EXISTS `oat_probe_alert_event` (
  `id` VARCHAR(64) PRIMARY KEY,
  `project_id` VARCHAR(64),
  `app_id` VARCHAR(64),
  `app_name` VARCHAR(128),
  `probe_key` VARCHAR(128),
  `session_id` VARCHAR(128),
  `address_ip` VARCHAR(64),
  `pid` VARCHAR(64),
  `system_dir` VARCHAR(512),
  `agent_version` VARCHAR(64),
  `event_type` VARCHAR(32),
  `event_time` DATETIME,
  `last_heartbeat_time` BIGINT,
  `offline_duration_millis` BIGINT,
  `message` TEXT,
  `notify_enabled` BOOLEAN,
  `notify_status` VARCHAR(32),
  `notify_channel` VARCHAR(64),
  `notify_response` TEXT,
  `notify_error` TEXT,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_app_event_time` (`app_id`, `event_time`),
  INDEX `idx_project_event_time` (`project_id`, `event_time`),
  INDEX `idx_notify_status` (`notify_status`),
  INDEX `idx_probe_key_event_time` (`probe_key`, `event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探针告警事件表';
