CREATE TABLE IF NOT EXISTS `oat_coverage_report` (
  `id` VARCHAR(64) PRIMARY KEY,
  `app_id` VARCHAR(64) NOT NULL,
  `version_number` VARCHAR(64),
  `repo_branch` VARCHAR(128),
  `repo_commit_id` VARCHAR(128),
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `last_processed_time` VARCHAR(64),
  `total_classes` BIGINT DEFAULT 0,
  `covered_classes` BIGINT DEFAULT 0,
  `total_methods` BIGINT DEFAULT 0,
  `covered_methods` BIGINT DEFAULT 0,
  `total_branches` BIGINT DEFAULT 0,
  `covered_branches` BIGINT DEFAULT 0,
  `total_branch_targets` BIGINT DEFAULT 0,
  `covered_branch_targets` BIGINT DEFAULT 0,
  `total_lines` BIGINT DEFAULT 0,
  `covered_lines` BIGINT DEFAULT 0,
  `total_complexity` INT DEFAULT 0,
  `report_type` TINYINT DEFAULT 0,
  `base_version_number` VARCHAR(64),
  `base_repo_commit_id` VARCHAR(128),
  `snapshot_fingerprint` VARCHAR(128),
  `snapshot_last_update_time` VARCHAR(64),
  `snapshot_count` INT,
  `snapshot_ids` TEXT,
  `inc_total_classes` BIGINT DEFAULT 0,
  `inc_covered_classes` BIGINT DEFAULT 0,
  `inc_total_lines` BIGINT DEFAULT 0,
  `inc_covered_lines` BIGINT DEFAULT 0,
  `inc_total_methods` BIGINT DEFAULT 0,
  `inc_covered_methods` BIGINT DEFAULT 0,
  `inc_total_branches` BIGINT DEFAULT 0,
  `inc_covered_branches` BIGINT DEFAULT 0,
  `inc_total_branch_targets` BIGINT DEFAULT 0,
  `inc_covered_branch_targets` BIGINT DEFAULT 0,
  `inc_total_complexity` INT DEFAULT 0,
  INDEX `idx_app_version_commit_type` (`app_id`, `version_number`, `repo_commit_id`, `report_type`),
  INDEX `idx_app_branch` (`app_id`, `repo_branch`),
  INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='覆盖率报告头表';
